from django.urls import path
# from .views import Register,Login,ImageUpload,Profile,UploadFileCustomer,UploadFileOwner,UploadProfile,AdminRegister,AdminLogin,ForgetPassword,EmailVerification,ResetPassword,ChangePassword
from .views import (
    Register,
    Login,
    Profile,
    UploadProfile,
    UploadFileCustomer,
    UploadFileOwner,
    UpdateUser,
    VehicleID,
    AdminRegister,
    AdminLogin,
    ForgetPassword,
    EmailVerification,
    ResetPassword,
    ChangePassword,
    Logout,
    CreditBalance,
    DebitBalance,
    AdminViewCustomer,
    AdminViewOwner,
    AdminViewPendingCustomer,
    AdminViewPendingOwner,
    AdminVerifyCustomer,
    AdminVerifyOwner,
)
urlpatterns = [
    path('register',Register.as_view(), name='register'),
    path('login',Login.as_view(), name='login'),
    path('profile',Profile.as_view(), name='profile'),
    path('upload/image',UploadProfile.as_view(), name='profile_image'),
    path('upload/customer/file',UploadFileCustomer.as_view(), name='file'),
    path('upload/owner/file',UploadFileOwner.as_view(), name='file'),
    path('update', UpdateUser.as_view(), name = 'update_user'),
    path('vehicleid', VehicleID.as_view(), name = 'Vehicle Update'),
    path('credit', CreditBalance.as_view(), name = 'credited_balance'),
    path('debit', DebitBalance.as_view(), name = 'debited_balance'),
    # path('owner',Owner.as_view(), name = 'owner'),
    # path('<usr>/upload',ImageUpload.as_view(), name='upload'),
    path('admin/signup',AdminRegister.as_view(), name = 'admin_signup'),
    path('admin/login',AdminLogin.as_view(), name = 'admin_login'),
    path('admin/view/customer', AdminViewCustomer.as_view(), name ='admin_customer_view'),
    path('admin/view/owner',AdminViewOwner.as_view(), name ='admin_owner_view'),
    path('admin/view/pendingcustomer', AdminViewPendingCustomer.as_view(), name = 'admin_view_pendingcustomer' ),
    path('admin/view/pendingowner', AdminViewPendingOwner.as_view(), name = 'admin_view_pendingowner'),
    path('admin/verify/customer/<id>', AdminVerifyCustomer.as_view(), name ='admin_verify_customer'),
    path('admin/verify/owner/<id>',AdminVerifyOwner.as_view(), name = 'admin_verify_owner'),
    path('forgetpassword', ForgetPassword.as_view(), name='forget_password'),
    path('verify/<id>/<token>', EmailVerification.as_view(), name ='verify_email'),
    path('reset/<id>/<token>', ResetPassword.as_view(), name ='reset_password'),
    path('changepassword', ChangePassword.as_view(), name = 'change_password'),
    path('logout',Logout.as_view(), name ='logout'),
]