# Generated by Django 5.0.6 on 2024-06-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_khaltipayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='home_paper',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='is_paperverified',
        ),
    ]
