# Generated by Django 5.0.6 on 2024-06-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parkinglocation',
            name='lat',
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
        migrations.AlterField(
            model_name='parkinglocation',
            name='lon',
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
    ]
