# Generated by Django 5.0.6 on 2024-06-24 17:07

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_reservation_reservation_alter_parkinglocation_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglocation',
            name='is_paperverified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkinglocation',
            name='parking_paper',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='document'),
        ),
    ]
