# Generated by Django 5.0.6 on 2024-05-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_parkinglocation_lat_alter_parkinglocation_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglocation',
            name='lat',
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
        migrations.AlterField(
            model_name='parkinglocation',
            name='lon',
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
    ]
